### ISSUE TITLE
Reusing buffers

### ISSUE THREAD

**Issue by edkolev** [jeetsukumaran/vim-filebeagle#18]
Thanks for this plugin, I literally use it daily!

I think I've run into an issue, but I'm not sure: filebeagle doesn't reuse buffers, instead it creates a fresh buffer each time it's used.

To reproduce:
1. open fresh vim
2. press `-` and run `:ls!` -- this shows filebeagle uses buf number 2
3. press `q`
4. press `-` and run `:ls!` -- filebeagle uses buf number 3. However, I would expect filebeagle to reuse buf number 2

Again, I'm not sure this is an issue, maybe by design filebeagle uses a new buffer each time it's executed.

**Comment by jeetsukumaran** [comment]
Hi, 

Yes, this is by design, to allow for multiple instances of FileBeagle open (on the same or different) directories simultaneously. FileBeagle *should* completely clear/delete the buffers when done (it is a bug if it doesn't), and so there should be no cost in terms of resource load, except possibly in terms of buffer index numbers ... ;)
