### ISSUE TITLE
Error with `set nohidden`

### ISSUE THREAD

**Issue by itspriddle** [jeetsukumaran/vim-filebeagle#19]
I hit an issue with FileBeagle when `set nohidden` is used. Possibly related to #10.

To duplicate, open a file and make sure that `set nohidden` is set. Edit the file but don't save it. Invoke FileBeagle (either `:FileBeagle` or `:FileBeagleBufferDir`). You'll see the following error:

```
Error detected while processing function filebeagle#FileBeagleOpen..43:
line   32:
E37: No write since last change (add ! to override)
Press ENTER or type command to continue
```

After pressing enter, the FileBeagle buffer is shown and you can choose a file. However, when you go back to the original file and attempt to save, you see an error:

```
E382: Cannot write, 'buftype' option is set
```

Here the buftype has been set to `nofile`.

I attempted to duplicate this with vim-vinegar and see a similar error, but the file browser is not displayed and the original buffer's buftype is unchanged so you can still save the file.

Would it be possible for FileBeagle to behave similarly?

**Comment by jeetsukumaran** [comment]
The situation is actually worse: if `set nohidden` is set, the FileBeagle contents are rendered inside the current buffer if the current buffer if there unmodified changes, because Vim refuses to open a new buffer.

A nice and polite solution would be for FileBeagle to temporarily `set hidden`, and then restore the previous state when closed. But this is problematical because we allow for multiple instances of FileBeagle to be invoked, even from the same buffer. So when a FileBeagle instance is invoked, it does not know whether or the current `hidden` state is that as set by user or as set by FileBeagle, so when restoring the state, it may restore the state set by another FileBeagle buffer instead of the native user state.

Alternatively, we can just store the native state of `hidden` the first time any FileBeagle instance is invoked and restore that, but that means that if the user changes the `hidden` state at any time, FileBeagle will get it wrong when restoring state.

At this point, I am going to push a commit that unconditionally makes sure `set hidden` is set the first time FileBeagle is invoked. That at least avoids the danger of clobbering the current buffer. Need to figure out an approach to cleanly record and restore the `hidden` state.

**Comment by jeetsukumaran** [comment]
Ok, the solution I am going for is to set hidden right before and then immediately unset right after opening the FileBeagle buffer, if hidden is not set. Let me know if this works.

**Comment by itspriddle** [comment]
@jeetsukumaran yep it works now. Thanks for taking a look!

**Comment by justinmk** [comment]
> After pressing enter, the FileBeagle buffer is shown and you can choose a file

At this point filebeagle should simply abort. If the user has `set nohidden` then he has explicitly said he doesn't want to leave an unmodified buffer, ever. 

I don't think this is related to #10 because I use `set hidden`.

**Comment by itspriddle** [comment]
> At this point filebeagle should simply abort. If the user has set nohidden then he has explicitly said he doesn't want to leave an unmodified buffer, ever.

I'd be fine with that approach too.

**Comment by jeetsukumaran** [comment]
> At this point filebeagle should simply abort. If the user has set nohidden then he has explicitly said he doesn't want to leave an unmodified buffer, ever.

I agree. Fixed to abort when called from unmodified buffer and `nohidden` is set.

**Comment by itspriddle** [comment]
09e4488b prevents FileBeagle opening at all if nohidden is set. Tweaking [L275](https://github.com/jeetsukumaran/vim-filebeagle/blob/09e4488b7e562da6082095898b5cd2f6a9557602/autoload/filebeagle.vim#L275) to `if !&hidden && &modified` seems to fix it. Thoughts?

**Comment by jeetsukumaran** [comment]
Makes perfect sense, and I have fixed it. Thanks!
