### ISSUE TITLE
default key bindings

### ISSUE THREAD

**Issue by justinmk** [jeetsukumaran/vim-filebeagle#6]
Some of the default key bindings shadow some useful operations. Some of these are minor, but the idea is that the user shouldn't have to worry about avoiding certain "reasonable" motions (we agreed that `f` and `t` are not "reasonable" in filebeagle).

* `gv` normally means "re-select the last visual selection". This is useful because visual-mode is useful in filebeagle, and it's conceivable that the user may reach for `gv` only to be surprised that it opens a possibly-unwanted file.
    * suggested alternative: Instead of having redundant `CTRL-` variants for o/v/s/t, why not use the `z` prefix for the "open in background" variants? (Mnemonic: `ctrl-z` in a terminal appears to "send Vim to the background".)

Specifically, I am suggesting:

```
Opening Files and Directories~
  <CR>  /  o       
  v         
  s        
  t            
-------------------------------------------------------------------------------
Opening Files and Directories in the Background~
  CTRL-<CR>  /  zo          
  zv
  zs
  zt
```

**Comment by robodendron** [comment]
Would it be possible to *not* disable the default keybindings `[".", "p", "P", "C", "x", "X", "r", "R", "i", "I", "a", "A", "D", "S", "U"]`? Their functionality is already disabled by setting `modifiable=off`, from what I can tell.

The reason why I'm proposing this: I'm using a [weird keyboard layout](http://adnw.de/) where `t` and `r` are in place of `j` and `k`, and because FileBeagle [sets the buffer filetype](https://github.com/jeetsukumaran/vim-filebeagle/blob/master/autoload/filebeagle.vim#L322) before it [creates the mappings](https://github.com/jeetsukumaran/vim-filebeagle/blob/master/autoload/filebeagle.vim#L325), I can't  use `.vim/after/ftplugin/filebeagle.vim` either. Alternatively, one could change the two lines (the call to `self.setup_buffer_opts()` and the one to `self.setup_buffer_keymaps()`) around, if that doesn't break anything.

I'm sorry if I was mistaken in posting in this thread; if you think this warrants a separate issue, I can post it as one no problem.

**Comment by jeetsukumaran** [comment]
Their functionality is not so much disabled as much as blocked with an annoying error message. 

Could you try hooking into the ``FileBeagleReadPre`` or ``FileBeagleReadPost`` autocommand events which fire just before/after the buffer is rendered?

Of the top of my head I cannot think of a reason not to invert the order the setup, and I could do this if the above is not acceptable for some reason.
